class ByToken:
    def __init__(self) -> None: ...
    def train(self, text_corpus: str, vocab_size: int, verbose: bool = False) -> None: ...
    def encode(self, text: str) -> list[int]: ...
    def decode(self, idx: list[int]) -> str: ...
